services:

  server:
    container_name: nginx
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - '80:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      db:
        condition: service_healthy
      php:
        condition: service_healthy

  php:
    build: 
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./src:/var/www/html
    healthcheck:
      test: ["CMD", "sh", "-c", "composer install && php artisan key:generate && php artisan migrate"]
      timeout: 30s
      retries: 10

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
